### PR TITLE
Python project

### PR DESCRIPTION
**Pull request by Amr2012Hashem**

### CODE REVIEW

**Comment by Amr2012Hashem** [comment]
@m-abdelrahman 
https://django-mssql.readthedocs.io/en/latest/quickstart.html

**Comment by m-abdelrahman** [comment]
@Amr2012Hashem 
no use

**Comment by Amr2012Hashem** [comment]
@m-abdelrahman ???

**Comment by m-abdelrahman** [comment]
after installing django_mssql still can't identify sql

**Comment by Amr2012Hashem** [comment]
https://stackoverflow.com/questions/9944204/setting-up-django-mssql-issues

**Comment by azbassiouny** [comment]
Did u try installing this one? 
@m-abdelrahman
https://pypi.org/project/django-pyodbc-azure/

**Comment by azbassiouny** [comment]
And read all the instructions in the link @m-abdelrahman

**Comment by azbassiouny** [comment]
@Amr2012Hashem 

i mean here

**Pull request merged**
